#
# commands
#

CCOMPILER=gcc
CCOMPILER_OPTIONS=-Wall -O3
CCOMPILER_LINKER_OPTIONS=-lm
PCX2MSX=bin/pcx2msx
PCX2SPR=bin/pcx2spr
PCX2MSXPLUS=bin/pcx2msx+
PCX2SPRPLUS=bin/pcx2spr+
PNG2MSX=bin/png2msx
PNG2SPR=bin/png2spr
PNG2SPRPLUS=bin/png2spr+
TMX2BIN=bin/tmx2bin
REMOVE=rm

#
# main makefile
#

include makefile.common
